export const BOARD_NAME_MAX_LENGTH =  7
export const BOARD_TITLE_MAX_LENGTH =  70
export const POST_NAME_MAX_LENGTH = 70
export const POST_SUBJECT_MAX_LENGTH = 140
export const POST_FILENAME_MAX_LENGTH = 1000
export const POST_COMMENT_MAX_LENGTH = 2000